package com.kodemon.persistence.enums;

import java.util.Arrays;
import java.util.List;

/**
 * Available names of Pokemon with their type
 *
 * @author Matej Poklemba
 */

public enum PokemonName {
    BULBASAUR("Bulbasaur", PokemonType.GRASS, PokemonType.POISON),
    IVYSAUR("Ivysaur", PokemonType.GRASS, PokemonType.POISON),
    VENUSAUR("Venusaur", PokemonType.GRASS, PokemonType.POISON),
    CHARMANDER("Charmander", PokemonType.FIRE),
    CHARMELEON("Charmeleon", PokemonType.FIRE),
    CHARIZARD("Charizard", PokemonType.FIRE, PokemonType.FLYING),
    SQUIRTLE("Squirtle", PokemonType.WATER),
    WARTORTLE("Wartortle", PokemonType.WATER),
    BLASTOISE("Blastoise", PokemonType.WATER),
    CATERPIE("Caterpie", PokemonType.BUG),
    METAPOD("Metapod", PokemonType.BUG),
    BUTTERFREE("Butterfree", PokemonType.BUG, PokemonType.FLYING),
    WEEDLE("Weedle", PokemonType.BUG, PokemonType.POISON),
    KAKUNA("Kakuna", PokemonType.BUG, PokemonType.POISON),
    BEEDRILL("Beedrill", PokemonType.BUG, PokemonType.POISON),
    PIDGEY("Pidgey", PokemonType.NORMAL, PokemonType.FLYING),
    PIDGEOTTO("Pidgeotto", PokemonType.NORMAL, PokemonType.FLYING),
    PIDGEOT("Pidgeot", PokemonType.NORMAL, PokemonType.FLYING),
    RATTATA("Rattata", PokemonType.NORMAL),
    RATICATE("Raticate", PokemonType.NORMAL),
    SPEAROW("Spearow", PokemonType.NORMAL, PokemonType.FLYING),
    FEAROW("Fearow", PokemonType.NORMAL, PokemonType.FLYING),
    EKANS("Ekans", PokemonType.POISON),
    ARBOK("Arbok", PokemonType.POISON),
    PIKACHU("Pikachu", PokemonType.ELECTRIC),
    RAICHU("Raichu", PokemonType.ELECTRIC),
    SANDSHREW("Sandshrew", PokemonType.GROUND),
    SANDSLASH("Sandslash", PokemonType.GROUND),
    NIDORAN_F("Nidoran♀", PokemonType.POISON),
    NIDORINA("Nidorina", PokemonType.POISON),
    NIDOQUEEN("Nidoqueen", PokemonType.POISON, PokemonType.GROUND),
    NIDORAN_M("Nidoran♂", PokemonType.POISON),
    NIDORINO("Nidorino", PokemonType.POISON),
    NIDOKING("Nidoking", PokemonType.POISON, PokemonType.GROUND),
    CLEFAIRY("Clefairy", PokemonType.NORMAL),
    CLEFABLE("Clefable", PokemonType.NORMAL),
    VULPIX("Vulpix", PokemonType.FIRE),
    NINETALES("Ninetales", PokemonType.FIRE),
    JIGGLYPUFF("Jigglypuff", PokemonType.NORMAL),
    WIGGLYTUFF("Wigglytuff", PokemonType.NORMAL),
    ZUBAT("Zubat", PokemonType.POISON, PokemonType.FLYING),
    GOLBAT("Golbat", PokemonType.POISON, PokemonType.FLYING),
    ODDISH("Oddish", PokemonType.GRASS, PokemonType.POISON),
    GLOOM("Gloom", PokemonType.GRASS, PokemonType.POISON),
    VILEPLUME("Vileplume", PokemonType.GRASS, PokemonType.POISON),
    PARAS("Paras", PokemonType.BUG, PokemonType.GRASS),
    PARASECT("Parasect", PokemonType.BUG, PokemonType.GRASS),
    VENONAT("Venonat", PokemonType.BUG, PokemonType.POISON),
    VENOMOTH("Venomoth", PokemonType.BUG, PokemonType.POISON),
    DIGLETT("Diglett", PokemonType.GROUND),
    DUGTRIO("Dugtrio", PokemonType.GROUND),
    MEOWTH("Meowth", PokemonType.NORMAL),
    PERSIAN("Persian", PokemonType.NORMAL),
    PSYDUCK("Psyduck", PokemonType.WATER),
    GOLDUCK("Golduck", PokemonType.WATER),
    MANKEY("Mankey", PokemonType.FIGHTING),
    PRIMEAPE("Primeape", PokemonType.FIGHTING),
    GROWLITHE("Growlithe", PokemonType.FIRE),
    ARCANINE("Arcanine", PokemonType.FIRE),
    POLIWAG("Poliwag", PokemonType.WATER),
    POLIWHIRL("Poliwhirl", PokemonType.WATER),
    POLIWRATH("Poliwrath", PokemonType.WATER, PokemonType.FIGHTING),
    ABRA("Abra", PokemonType.PSYCHIC),
    KADABRA("Kadabra", PokemonType.PSYCHIC),
    ALAKAZAM("Alakazam", PokemonType.PSYCHIC),
    MACHOP("Machop", PokemonType.FIGHTING),
    MACHOKE("Machoke", PokemonType.FIGHTING),
    MACHAMP("Machamp", PokemonType.FIGHTING),
    BELLSPROUT("Bellsprout", PokemonType.GRASS, PokemonType.POISON),
    WEEPINBELL("Weepinbell", PokemonType.GRASS, PokemonType.POISON),
    VICTREEBEL("Victreebel", PokemonType.GRASS, PokemonType.POISON),
    TENTACOOL("Tentacool", PokemonType.WATER, PokemonType.POISON),
    TENTACRUEL("Tentacruel", PokemonType.WATER, PokemonType.POISON),
    GEODUDE("Geodude", PokemonType.ROCK, PokemonType.GROUND),
    GRAVELER("Graveler", PokemonType.ROCK, PokemonType.GROUND),
    GOLEM("Golem", PokemonType.ROCK, PokemonType.GROUND),
    PONYTA("Ponyta", PokemonType.FIRE),
    RAPIDASH("Rapidash", PokemonType.FIRE),
    SLOWPOKE("Slowpoke", PokemonType.WATER, PokemonType.PSYCHIC),
    SLOWBRO("Slowbro", PokemonType.WATER, PokemonType.PSYCHIC),
    MAGNEMITE("Magnemite", PokemonType.ELECTRIC),
    MAGNETON("Magneton", PokemonType.ELECTRIC),
    FARFETCHD("Farfetch'd", PokemonType.NORMAL, PokemonType.FLYING),
    DODUO("Doduo", PokemonType.NORMAL, PokemonType.FLYING),
    DODRIO("Dodrio", PokemonType.NORMAL, PokemonType.FLYING),
    SEEL("Seel", PokemonType.WATER),
    DEWGONG("Dewgong", PokemonType.WATER, PokemonType.ICE),
    GRIMER("Grimer", PokemonType.POISON),
    MUK("Muk", PokemonType.POISON),
    SHELLDER("Shellder", PokemonType.WATER),
    CLOYSTER("Cloyster", PokemonType.WATER, PokemonType.ICE),
    GASTLY("Gastly", PokemonType.GHOST, PokemonType.POISON),
    HAUNTER("Haunter", PokemonType.GHOST, PokemonType.POISON),
    GENGAR("Gengar", PokemonType.GHOST, PokemonType.POISON),
    ONIX("Onix", PokemonType.ROCK, PokemonType.GROUND),
    DROWZEE("Drowzee", PokemonType.PSYCHIC),
    HYPNO("Hypno", PokemonType.PSYCHIC),
    KRABBY("Krabby", PokemonType.WATER),
    KINGLER("Kingler", PokemonType.WATER),
    VOLTORB("Voltorb", PokemonType.ELECTRIC),
    ELECTRODE("Electrode", PokemonType.ELECTRIC),
    EXEGGCUTE("Exeggcute", PokemonType.GRASS, PokemonType.PSYCHIC),
    EXEGGUTOR("Exeggutor", PokemonType.GRASS, PokemonType.PSYCHIC),
    CUBONE("Cubone", PokemonType.GROUND),
    MAROWAK("Marowak", PokemonType.GROUND),
    HITMONLEE("Hitmonlee", PokemonType.FIGHTING),
    HITMONCHAN("Hitmonchan", PokemonType.FIGHTING),
    LICKITUNG("Lickitung", PokemonType.NORMAL),
    KOFFING("Koffing", PokemonType.POISON),
    WEEZING("Weezing", PokemonType.POISON),
    RHYHORN("Rhyhorn", PokemonType.GROUND, PokemonType.ROCK),
    RHYDON("Rhydon", PokemonType.GROUND, PokemonType.ROCK),
    CHANSEY("Chansey", PokemonType.NORMAL),
    TANGELA("Tangela", PokemonType.GRASS),
    KANGASKHAN("Kangaskhan", PokemonType.NORMAL),
    HORSEA("Horsea", PokemonType.WATER),
    SEADRA("Seadra", PokemonType.WATER),
    GOLDEEN("Goldeen", PokemonType.WATER),
    SEAKING("Seaking", PokemonType.WATER),
    STARYU("Staryu", PokemonType.WATER),
    STARMIE("Starmie", PokemonType.WATER, PokemonType.PSYCHIC),
    MRMIME("Mr. Mime", PokemonType.PSYCHIC),
    SCYTHER("Scyther", PokemonType.BUG, PokemonType.FLYING),
    JYNX("Jynx", PokemonType.ICE, PokemonType.PSYCHIC),
    ELECTABUZZ("Electabuzz", PokemonType.ELECTRIC),
    MAGMAR("Magmar", PokemonType.FIRE),
    PINSIR("Pinsir", PokemonType.BUG),
    TAUROS("Tauros", PokemonType.NORMAL),
    MAGIKARP("Magikarp", PokemonType.WATER),
    GYARADOS("Gyarados", PokemonType.WATER, PokemonType.FLYING),
    LAPRAS("Lapras", PokemonType.WATER, PokemonType.ICE),
    DITTO("Ditto", PokemonType.NORMAL),
    EEVEE("Eevee", PokemonType.NORMAL),
    VAPOREON("Vaporeon", PokemonType.WATER),
    JOLTEON("Jolteon", PokemonType.ELECTRIC),
    FLAREON("Flareon", PokemonType.FIRE),
    PORYGON("Porygon", PokemonType.NORMAL),
    OMANYTE("Omanyte", PokemonType.ROCK, PokemonType.WATER),
    OMASTAR("Omastar", PokemonType.ROCK, PokemonType.WATER),
    KABUTO("Kabuto", PokemonType.ROCK, PokemonType.WATER),
    KABUTOPS("Kabutops", PokemonType.ROCK, PokemonType.WATER),
    AERODACTYL("Aerodactyl", PokemonType.ROCK, PokemonType.FLYING),
    SNORLAX("Snorlax", PokemonType.NORMAL),
    ARTICUNO("Articuno", PokemonType.ICE, PokemonType.FLYING),
    ZAPDOS("Zapdos", PokemonType.ELECTRIC, PokemonType.FLYING),
    MOLTRES("Moltres", PokemonType.FIRE, PokemonType.FLYING),
    DRATINI("Dratini", PokemonType.DRAGON),
    DRAGONAIR("Dragonair", PokemonType.DRAGON),
    DRAGONITE("Dragonite", PokemonType.DRAGON, PokemonType.FLYING),
    MEWTWO("Mewtwo", PokemonType.PSYCHIC),
    MEW("Mew", PokemonType.PSYCHIC);

    private PokemonType[] types;
    private String name;

    PokemonName(String name, PokemonType... types) {
        this.name = name;
        this.types = types;
    }

    public static List<PokemonName> getInitialPokemon() {
        return Arrays.asList(BULBASAUR, CHARMANDER, SQUIRTLE);
    }

    public PokemonType[] getTypes() {
        return this.types;
    }

    public String getName() {
        return this.name;
    }
}
